# Generated by Django 5.1.1 on 2026-01-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodgram_api", "0003_alter_shoppingcart_recipe_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="measurement_unit",
            field=models.CharField(max_length=10, verbose_name="Единица измерения"),
        ),
    ]
