# Generated by Django 5.1.1 on 2026-02-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_favorite_user_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
