# Generated by Django 5.1.1 on 2026-02-11 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_subscribe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Имя пользователя может содержать только буквы, цифры и символы",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
