# Generated by Django 5.1.1 on 2026-02-14 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_favorite_recipe_alter_favorite_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="users/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Имя пользователя может содержать только буквы, цифры и символы",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="Логин",
            ),
        ),
    ]
