# Generated by Django 5.1.1 on 2026-01-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribe",
            options={"verbose_name": "Подписчик", "verbose_name_plural": "Подписчики"},
        ),
    ]
